# Generated by Django 4.1.1 on 2022-10-21 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentId", models.CharField(max_length=20, null=True)),
                (
                    "age",
                    models.PositiveBigIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(17),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "sex",
                    models.PositiveBigIntegerField(
                        choices=[(0, "Female"), (1, "Male")], null=True
                    ),
                ),
                (
                    "course",
                    models.PositiveBigIntegerField(
                        choices=[
                            (1, "BS Community Development"),
                            (2, "BS Information Technology"),
                            (3, "BS Computer Science"),
                            (4, "BS Social Work"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.PositiveBigIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "status",
                    models.PositiveBigIntegerField(
                        choices=[
                            (1, "Low (₱9,520-₱19,040)"),
                            (2, "Low Middle (₱19,040-₱38,080)"),
                            (3, "Middle (₱38,080-₱66,640)"),
                            (4, "Upper Middle (₱66,640-₱114,240)"),
                            (5, "Upper but not rich (₱114,240-₱190,400)"),
                            (6, "Rich (At least ₱190,400)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "support",
                    models.PositiveBigIntegerField(
                        choices=[(0, "NO"), (1, "YES")], null=True
                    ),
                ),
                (
                    "scholar",
                    models.PositiveBigIntegerField(
                        choices=[(0, "NO"), (1, "YES")], null=True
                    ),
                ),
                (
                    "wstud",
                    models.PositiveBigIntegerField(
                        choices=[(0, "NO"), (1, "YES")], null=True
                    ),
                ),
                (
                    "personality",
                    models.PositiveBigIntegerField(
                        choices=[
                            (0, "ISTJ"),
                            (1, "ESFJ"),
                            (2, "ENTP"),
                            (3, "ISFJ"),
                            (4, "ENFJ"),
                            (5, "INFJ"),
                            (6, "ISFP"),
                            (7, "INTJ"),
                            (8, "ENTJ"),
                            (9, "ESTP"),
                            (10, "INFP"),
                            (11, "ESFP"),
                            (12, "ESTJ"),
                            (13, "ENFP"),
                            (14, "ISTP"),
                            (15, "INTP"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "TM1",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM2",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM3",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM4",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM5",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM6",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "TM7",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "CAP1",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "CAP2",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "CAP3",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "CAP4",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS1",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS2",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS3",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS4",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS5",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS6",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "GSS7",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "EP1",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "EP2",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "EP3",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "EP4",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "EP5",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "NT1",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "NT2",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "NT3",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "desktop",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "laptop",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "mobile",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "tablet",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "wifi",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "p_wifi",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "c_data",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "hotspot",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "vh_speed",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "h_speed",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "m_speed",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "l_speed",
                    models.PositiveBigIntegerField(
                        choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                        null=True,
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("predictions", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
