# Generated by Django 4.1.1 on 2022-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="EP6",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")], null=True
            ),
        ),
    ]
