# Generated by Django 4.1.1 on 2022-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0002_data_ep6"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data", name="gpa", field=models.FloatField(null=True),
        ),
    ]
