# Generated by Django 4.1.1 on 2022-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0008_alter_data_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="CAP1",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="CAP1: I attend class regularly.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="CAP2",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="CAP2: I get to class early or on time.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="CAP3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="CAP3: I come to class prepared, having completed the reading.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="CAP4",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="CAP4: I always find a comfortable place for me when I’m listening to the lecture or watching lecture’s video.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP1",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP1: I review older material first when studying for exams.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP2",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP2: When studying for exams, I review over several chapter.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP3: I study for exams at least five days in advance.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP4",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP4: I make up exam questions and answer them as I study",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP5",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP5: I make up exam questions using the same format that the actual exam will use.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="EP6",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="EP6: I review for exams with a peer or a small study group.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS1",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS1: I plan sufficient time to get assignments done.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS2",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS2: I turn in all assignments on time.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS3: I use index cards to write down important information and then review that information when I am “waiting” around.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS4",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS4: I work on more difficult task first.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS5",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS5: I set specific goals for each subject.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS6",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS6: I have a regular study area that is free of distractions.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="GSS7",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="GSS7: I take breaks when I study.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="NT1",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="NT1: I take organized and legible notes during class.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="NT2",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="NT2: I review and revise my notes soon after class.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="NT3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="NT3: I take notes as I read my assignments.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM1",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM1: I have a study schedule with times set aside to study each subject.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM2",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM2: I use my free time between classes for reading or reviewing.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM3: I balance my study time with recreation and leisure time.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM4",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM4: I have a calendar of the semester and it is marked with exam dates, project due dates and assignments.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM5",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM5: I keep a weekly schedule of my classes and activities.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM6",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM6: I use daily “to do” lists.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="TM7",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="TM7: I study on the weekends.",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="c_data",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Cellular Data",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="desktop",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Desktop",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="h_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="High",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="hotspot",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Hotspot Tethering",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="l_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Light",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="laptop",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Laptop",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="m_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Moderate",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="mobile",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Mobile Phone",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="p_wifi",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Prepaid Wi-Fi",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="personality",
            field=models.PositiveBigIntegerField(
                choices=[
                    (0, "ISTJ"),
                    (1, "ESFJ"),
                    (2, "ENTP"),
                    (3, "ISFJ"),
                    (4, "ENFJ"),
                    (5, "INFJ"),
                    (6, "ISFP"),
                    (7, "INTJ"),
                    (8, "ENTJ"),
                    (9, "ESTP"),
                    (10, "INFP"),
                    (11, "ESFP"),
                    (12, "ESTJ"),
                    (13, "ENFP"),
                    (14, "ISTP"),
                    (15, "INTP"),
                ],
                null=True,
                verbose_name="Personality Type",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="scholar",
            field=models.PositiveBigIntegerField(
                choices=[(0, "NO"), (1, "YES")],
                null=True,
                verbose_name="Are you a Scholar?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="status",
            field=models.PositiveBigIntegerField(
                choices=[
                    (1, "Low (₱9,520-₱19,040)"),
                    (2, "Low Middle (₱19,040-₱38,080)"),
                    (3, "Middle (₱38,080-₱66,640)"),
                    (4, "Upper Middle (₱66,640-₱114,240)"),
                    (5, "Upper but not rich (₱114,240-₱190,400)"),
                    (6, "Rich (At least ₱190,400)"),
                ],
                null=True,
                verbose_name="Socio-Economic Status",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="studentId",
            field=models.CharField(max_length=20, null=True, verbose_name="Student ID"),
        ),
        migrations.AlterField(
            model_name="data",
            name="support",
            field=models.PositiveBigIntegerField(
                choices=[(0, "NO"), (1, "YES")],
                null=True,
                verbose_name="Family Support?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="tablet",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Tablet",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="vh_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Very High",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="wifi",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Wi-Fi",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="wstud",
            field=models.PositiveBigIntegerField(
                choices=[(0, "NO"), (1, "YES")],
                null=True,
                verbose_name="Are you a working student?",
            ),
        ),
    ]
