# Generated by Django 4.1.1 on 2022-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0010_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="stud_course",
            field=models.CharField(
                choices=[
                    (1, "BS Community Development"),
                    (2, "BS Information Technology"),
                    (3, "BS Computer Science"),
                    (4, "BS Social Work"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="stud_year",
            field=models.CharField(
                choices=[(2, "2nd Year"), (3, "3rd Year"), (4, "4th Year")],
                max_length=100,
                null=True,
            ),
        ),
    ]
