# Generated by Django 4.1.1 on 2022-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0011_students_stud_course_students_stud_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="phone",
            field=models.PositiveBigIntegerField(max_length=100, null=True),
        ),
    ]
