# Generated by Django 4.1.1 on 2022-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0012_alter_students_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="stud_course",
            field=models.CharField(
                choices=[
                    ("BSCD", "BS Community Development"),
                    ("BSIT", "BS Information Technology"),
                    ("BSCS", "BS Computer Science"),
                    ("BSSW", "BS Social Work"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="stud_year",
            field=models.PositiveBigIntegerField(
                choices=[(2, "2nd Year"), (3, "3rd Year"), (4, "4th Year")],
                max_length=100,
                null=True,
            ),
        ),
    ]
