# Generated by Django 4.1.1 on 2022-12-07 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("thesis", "0013_alter_students_stud_course_alter_students_stud_year"),
    ]

    operations = [
        migrations.RenameModel(old_name="students", new_name="student",),
    ]
