# Generated by Django 4.1.1 on 2022-12-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0015_data_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data", old_name="student", new_name="students",
        ),
    ]
