# Generated by Django 4.1.1 on 2022-12-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0016_rename_student_data_students"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="CAP1",),
        migrations.RemoveField(model_name="data", name="EP4",),
        migrations.RemoveField(model_name="data", name="EP6",),
        migrations.RemoveField(model_name="data", name="GSS1",),
        migrations.RemoveField(model_name="data", name="GSS5",),
        migrations.RemoveField(model_name="data", name="TM1",),
        migrations.RemoveField(model_name="data", name="TM2",),
        migrations.RemoveField(model_name="data", name="hotspot",),
        migrations.RemoveField(model_name="data", name="m_speed",),
        migrations.RemoveField(model_name="data", name="p_wifi",),
        migrations.RemoveField(model_name="data", name="support",),
        migrations.RemoveField(model_name="data", name="vh_speed",),
    ]
