# Generated by Django 4.1.1 on 2022-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0017_remove_data_cap1_remove_data_ep4_remove_data_ep6_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="data",
            name="c_data",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use Cellular Data for internet connectivity?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="desktop",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use Desktop for academic purposes?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="h_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Does your internet connection frequently in high speed?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="l_speed",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="Does your internet connection frequently in light speed?",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="laptop",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use Laptop for academic purposes",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="mobile",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use Mobile Phone for academic purposes",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="tablet",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use Tablet for academic purposes",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="wifi",
            field=models.PositiveBigIntegerField(
                choices=[(1, "Always"), (2, "Sometimes"), (3, "Never")],
                null=True,
                verbose_name="How often do you use WiFi for internet connectivity?",
            ),
        ),
    ]
