# Generated by Django 4.1.1 on 2022-12-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0018_student_profile_pic_alter_data_c_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="data", name="studentId",),
    ]
