# Generated by Django 4.1.1 on 2022-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0019_remove_data_studentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="studentId",
            field=models.CharField(max_length=20, null=True, verbose_name="Student ID"),
        ),
    ]
