# Generated by Django 4.1.1 on 2022-12-13 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0020_data_studentid"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="profile_pic",),
        migrations.AlterField(
            model_name="data",
            name="gpa",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
