# Generated by Django 4.1.1 on 2022-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0021_remove_student_profile_pic_alter_data_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
