# Generated by Django 4.1.1 on 2022-12-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0023_alter_student_profile_pic_alter_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="studentId",
            field=models.CharField(
                choices=[("1st Sem", "1st Sem"), ("2nd Sem", "2nd Sem")],
                max_length=100,
                null=True,
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="stud_year",
            field=models.PositiveBigIntegerField(
                choices=[(2, "2nd Year"), (3, "3rd Year"), (4, "4th Year")], null=True
            ),
        ),
    ]
