# Generated by Django 4.1.5 on 2023-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0025_alter_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="stud_course",
            field=models.CharField(
                choices=[
                    (1, "BS Community Development"),
                    (2, "BS Information Technology"),
                    (3, "BS Computer Science"),
                    (4, "BS Social Work"),
                ],
                max_length=100,
                null=True,
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="stud_year",
            field=models.PositiveBigIntegerField(
                choices=[(2, "2nd Year"), (3, "3rd Year"), (4, "4th Year")],
                null=True,
                verbose_name="Year",
            ),
        ),
    ]
