# Generated by Django 4.1.5 on 2023-01-08 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0028_alter_student_stud_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stud_age",
            field=models.PositiveBigIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(17),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="stud_sex",
            field=models.PositiveBigIntegerField(
                choices=[(0, "Female"), (1, "Male")], null=True
            ),
        ),
    ]
