# Generated by Django 4.1.5 on 2023-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thesis", "0029_student_stud_age_student_stud_sex"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="stud_age",),
        migrations.RemoveField(model_name="student", name="stud_sex",),
    ]
