# Generated by Django 3.2.16 on 2023-01-27 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0031_student_stud_age_student_stud_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='data',
            name='tablet',
        ),
        migrations.AddField(
            model_name='data',
            name='GSS1',
            field=models.PositiveBigIntegerField(choices=[(1, 'Always'), (2, 'Sometimes'), (3, 'Never')], null=True, verbose_name='GSS1: I plan sufficient time to get assignments done.'),
        ),
        migrations.AddField(
            model_name='data',
            name='GSS5',
            field=models.PositiveBigIntegerField(choices=[(1, 'Always'), (2, 'Sometimes'), (3, 'Never')], null=True, verbose_name='GSS5: I set specific goals for each subject.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_age',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(40)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_sex',
            field=models.PositiveBigIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True, verbose_name='Sex'),
        ),
    ]
