# Generated by Django 3.2.16 on 2023-03-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0033_alter_data_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.PositiveBigIntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis.student', verbose_name="Student's No."),
        ),
    ]
