# Generated by Django 3.2.16 on 2023-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0035_alter_data_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datePredicted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
