# Generated by Django 4.1.5 on 2023-03-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0036_data_datepredicted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
